### ISSUE TITLE
Closest match should also be automatically selected.

### ISSUE THREAD

**Issue by scwu** [pennlabs/pcr#109]
Departments are off the page - which make them even less prominent. More importantly - when I type a department, the department should be auto-selected.

![screenshot 2014-04-19 18 03 44](https://cloud.githubusercontent.com/assets/1690945/2749578/87bae602-c80e-11e3-973b-097d141d5c5d.png)

**Comment by sigmachirality** [comment]
search bar has been completely redesigned with 2019 React rewrite, closing this issue
