### ISSUE TITLE
script failing on About and FAQ pages

### ISSUE THREAD

**Issue by scwu** [pennlabs/pcr#111]
It's worth noting the issue occurs on any page that isn't the home page or a course page. The error occurs on the FAQ page, and About Page and only on page load.

I looked at the source the issue seems to be that on both of these pages, lines 27-31 of the html pages (faq.html and about.html) the function init_search_box is unnecessarily called with only a single parameter. 

The function appears to only be called once a user begins typing in the searchbox, so there doesn't seem to be a need for the following code block in those two files. (I also doubled checked the home page and course pages-- these lines aren't present indicating they are unnecessary):

  <script type="text/javascript">
    $(document).ready(function() {
      init_search_box("../");
    });
  </script>

Removing these lines should take care of the issue, and not break any functionality :).

**Comment by sigmachirality** [comment]
JQuery has been phased out in favor of React.
