### ISSUE TITLE
Feature idea: registrar integration

### ISSUE THREAD

**Issue by awiss** [pennlabs/pcr#118]
I had an idea while looking on the PHIL dept page for a good course to take next semester. It would be nice to filter by courses available next semester, and maybe also further filter by open courses on this page. Instructor page, too. I kinda wanna filter by courses said instructor is teaching next semester.

**Comment by sigmachirality** [comment]
Though PCP occupies this problem space, we can look into features that would make finding current courses easier on professor pages and the like as suggested.
