### ISSUE TITLE
Is apps.searchbar.views still used?

### ISSUE THREAD

**Issue by Ceasar** [pennlabs/pcr#136]
Is https://github.com/pennlabs/pcr/blob/master/apps/searchbar/views.py used anywhere?

I was playing around refactoring this a little and it doesn't seem to be used. You can delete it, and the app will still function, since the autocomplete actually relies on https://github.com/pennlabs/pcr/blob/master/media/autocomplete_data.json.

It should also probably have made been obsolete by the API search end point, as described in its spec: https://github.com/pennlabs/pcr-api-spec/tree/master/specs/search

@awiss Looks like you added that file.

**Comment by sigmachirality** [comment]
@ezwang thoughts?

**Comment by sigmachirality** [comment]
backend has been rewritten a lot, code cleanup is a constant process and we will look into additional refactoring but it is unlikely this ticket still applies
