### ISSUE TITLE
General Design Updates

### ISSUE THREAD

**Issue by derekjobst** [pennlabs/pcr#137]
Many of these things are already mentioned elsewhere, but this is a nice summary:
1. Design needs more contrast 
2. On navbar search: 
3. The dropdown blends into the white box for the listing 
4. The lack of margins and rounded corners is weird 
5. The first result isn't autoselected 
6. Selected style is weird (larger font, changes menu size) 
7. Spacing/font sizes in footer is off 
8. Button highlight styles are inconsistent (on course page, for example) 
9. Default button style is different on front page from on course page 
10. Some buttons on course page are times new roman 
11. Pressing plus to expand all, then collapsing one, toggles the contract all back to expand all. This should be investigated.

**Comment by sigmachirality** [comment]
Issues are either resolved or not applicable to current PCR frontend.
