### ISSUE TITLE
OIDD and OPIM classes not crosslisted properly

### ISSUE THREAD

**Issue by esqu1** [pennlabs/pcr#211]
![screenshot from 2016-11-05 20 22 36](https://cloud.githubusercontent.com/assets/7027037/20034504/29d7b630-a396-11e6-8bc2-af67d5f4f549.png)
![screenshot from 2016-11-05 20 25 58](https://cloud.githubusercontent.com/assets/7027037/20034503/29d480f0-a396-11e6-83f6-1cc1060b1bbe.png)
OPIM recently became OIDD but the departments are not linked on PCR.

**Comment by sigmachirality** [comment]
Don't want to edit the data that we're given too much, but def will consider what to do about this. Moving to clubhouse~
