### ISSUE TITLE
Update SSL certificate chain and allowed ciphers

### ISSUE THREAD

**Issue by adelq** [pennlabs/pcr#228]
See Penn's security scan for details

**Comment by sigmachirality** [comment]
@ezwang can you clarify on what this means

**Comment by ezwang** [comment]
I think we did this at some point, @ArmaanT may know more.

This is just updating the Nginx rules to disallow some older insecure cryptography methods. The downside of this is that really ancient browsers, like IE 6 or something, won't be able to use the site anymore (with all our fancy React stuff, I doubt older browsers can use it now unless we use a ton of polyfills).

**Comment by sigmachirality** [comment]
Platform seems to have taken care of this, and we don't need to worry about support for pre-chromium ie
