### ISSUE TITLE
Recent Title is selecting the oldest title, not the newest one

### ISSUE THREAD

**Issue by adamdom** [pennlabs/pcr#233]
![image](https://cloud.githubusercontent.com/assets/14148605/24083981/00141664-0cb8-11e7-9c1b-666059d18c99.png)

**Comment by sigmachirality** [comment]
React rewrite has rendered this issue defunct, however we should look into whether re-adding (RECENT TITLE) and also maybe giving which semester it's from through the title is a good idea or not.
