### ISSUE TITLE
"We are performing maintenance" page during updates 

### ISSUE THREAD

**Issue by adamdom** [pennlabs/pcr#235]

**Comment by sigmachirality** [comment]
@ezwang Does PCR still still work during updates/deploy?

**Comment by ezwang** [comment]
PCR still works during updates, we put the data in another database and then switch over once the updates are done.

It might also be nice to have a maintenance page when we have to take PCR down for some reason.

**Comment by sigmachirality** [comment]
Since PCR normally shouldn't go down for extended periods of time ever, this is not a high priority issue rn
