### ISSUE TITLE
Course Cart doesn't show correct ratings

### ISSUE THREAD

**Issue by esqu1** [pennlabs/pcr#246]
![image](https://user-images.githubusercontent.com/7027037/28731116-98abccf6-73a0-11e7-8564-a1d2ac8fe472.png)
![image](https://user-images.githubusercontent.com/7027037/28731121-a296592a-73a0-11e7-8985-d092a4e5ca87.png)

The ratings in the course cart do not match up with the selected professor. It does not seem to select the "most recent section" either.

**Comment by sigmachirality** [comment]
Still an issue despite the React rewrite of course cart!

**Comment by sigmachirality** [comment]
Tabling due to plans to integrate more with https://penncourseplan.com/ which may render the course cart defunct
