### ISSUE TITLE
Different search box text color between Firefox and Chrome

### ISSUE THREAD

**Issue by adelq** [pennlabs/pcr#253]
Not a big deal, but the inconsistency is something to be aware of

**Chrome**
![image](https://user-images.githubusercontent.com/929309/32894848-1bc40e8e-caac-11e7-9662-2b30bf2137dc.png)

**Firefox**
![image](https://user-images.githubusercontent.com/929309/32894868-23b0b3ea-caac-11e7-9bd7-83f5bd878cac.png)

**Comment by sigmachirality** [comment]
not reproducible on React frontend
