### ISSUE TITLE
Showing courses by nonexistant Aliases

### ISSUE THREAD

**Issue by kylehg** [pennlabs/pcr#83]
If a course code was crosslisted _once_, its liable to show up as the crosslisting even for instances that don't have the crosslisting. Example:

For [Prof. Rudra Sil](https://beta.penncoursereview.com/instructor/988-RUDRA-SIL), the three sections of PSCI-598 he taught all show up as (and link to) PPE-475, even though the only time PSCI-598 was cross-listed with PPE-475 was Fall 2007.

This may be related to / solvable by #79.

**Comment by sigmachirality** [comment]
Still an issue on contemporary PCR, PSCI-598 is implied to be crosslisted to PPE-475 though 475 was only crosslisted to 598 once.
